management:
  server:
    port: 8187

spring:
  server:
    protocol: http
    url: localhost:8087
  data:
    jpa.repositories.enabled: true
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
  datasource:
    url: jdbc:log4jdbc:h2:mem:testdb                       # With no spy: jdbc:h2:mem:testdb
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy # With no spy: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always

logging:
  level:
    org:
      springframework:
        integration:
          sftp: trace
      hibernate:
        type: error
