openapi: 3.0.1
info:
  title: Inditex Retail Prices Service API
  description: Inditex Retail Prices Service API
  version: 1.0.
paths:
  /price/{brandId}/{productId}/{date}:
    get:
      operationId: getPrice
      summary: Get Price
      parameters:
          - in: path
            name: brandId
            schema:
              type: integer
              format: int64
            required: true
            description: Brand ID
          - in: path
            name: productId
            schema:
              type: integer
              format: int64
            required: true
            description: Product ID
          - in: path
            name: date
            schema:
              type: string
              format: date-time
            required: true
            description: Application date

      responses:
        200:
          description: Price found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Price'
        404:
          description: Price not found
components:
  schemas:
    Price:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Price ID
        brandId:
          type: integer
          format: int64
          description: Brand ID
          example: 1
        productId:
          type: integer
          format: int64
          description: Product ID
          example: 35455
        startDate:
          type: string
          format: date-time
          description: Start date in which the price list applies
        endDate:
          type: string
          format: date-time
          description: End date in which the price list applies
        currency:
          type: string
          enum: [EUR, USD, GBP]
          description: Price currency ISO 4217 code
          example: ISO
        price:
          type: number
          format: float
          description: Price amount in currency abobe. For security reasons, this value will be rounded to the fractional palces admitted by the currency
          example: 17.95
